problem_lp = {'25fv47.mps';'80bau3b.mps';'adlittle.mps';'afiro.mps';...
  'agg.mps';'agg2.mps';'agg3.mps';'bandm.mps';'beaconfd.mps';...
  'blend.mps';'bnl1.mps';'bnl2.mps';'boeing1.mps';'boeing2.mps';'bore3d.mps';'brandy.mps';...
  'capri.mps';'cycle.mps';'czprob.mps';'d2q06c.mps';'d6cube.mps';...
  'degen2.mps';'degen3.mps';'dfl001.mps';'e226.mps';'etamacro.mps';...
  'fffff800.mps';'finnis.mps';'fit1d.mps';'fit1p.mps';'fit2d.mps';...
  'fit2p.mps';'ganges.mps';'gfr d- pnc.mps';'greenbea.mps';...
  'greenbeb.mps';'grow7.mps';'grow15.mps';'grow22.mps';'israel.mps';...
  'kb2.mps';'lotfi.mps';'maros.mps';'maro s- r7.mps';'modszk1.mps';...
  'nesm.mps';'perold.mps';'pilot.ja.mps';'pilot.mps';'pilot.we.mps';...
  'pilot4.mps';'pilot87.mps';'pilotnov.mps';'recipe.mps';...
  'sc50a.mps';'sc50b.mps';'sc105.mps';'sc205.mps';'scagr7.mps';...
  'scagr25.mps';'scfxm1.mps';'scfxm2.mps';'scfxm3.mps';...
  'scorpion.mps';'scrs8.mps';'scsd1.mps';'scsd6.mps';'scsd8.mps';...
  'sctap1.mps';'sctap2.mps';'sctap3.mps';'seba.mps';'share1b.mps';...
  'share2b.mps';'shell.mps';'ship04l.mps';'ship04s.mps';...
  'ship08l.mps';'ship08s.mps';'ship12l.mps';'ship12s.mps';...
  'sierra.mps';'stair.mps';'standata.mps';'standgub.mps';...
  'standmps.mps';'stocfor1.mps';'stocfor2.mps';'tuff.mps';...
  'vtp.base.mps';'wood1p.mps';'woodw.mps'};

problem_qp_brunel = {'q25fv47.qps';'qadlittl.qps';'qafiro.qps';'qbandm.qps';...
  'qbeaconf.qps';'qbore3d.qps';'qbrandy.qps';...
  'qcapri.qps';'qe226.qps';'qetamacr.qps';...
  'qfffff80.qps';'qforplan.qps';'qgfrdxpn.qps';'qgrow7.qps';'qgrow15.qps';'qgrow22.qps';'qisrael.qps';...
  'qpilotno.qps';'qrecipe.qps';...
  'qsc205.qps';'qscagr7.qps';...
  'qscagr25.qps';'qscfxm1.qps';'qscfxm2.qps';'qscfxm3.qps';...
  'qscorpio.qps';'qscrs8.qps';'qscsd1.qps';'qscsd6.qps';'qscsd8.qps';...
  'qsctap1.qps';'qsctap2.qps';'qsctap3.qps';'qseba.qps';'qshare1b.qps';...
  'qshare2b.qps';'qshell.qps';'qship04l.qps';'qship04s.qps';...
  'qship08l.qps';'qship08s.qps';'qship12l.qps';'qship12s.qps';...
  'qsierra.qps';'qstair.qps';'qstandat.qps'};

problem_qp_cute = {'aug2d.qps';'aug2dc.qps';'aug2dcqp.qps';'aug2dqp.qps';...
  'aug3d.qps';'aug3dc.qps';'aug3dcqp.qps';'aug3dqp.qps';'cvxqp1_l.qps';...
  'cvxqp1_m.qps';'cvxqp1_s.qps';'cvxqp2_l.qps';'cvxqp2_m.qps';...
  'cvxqp2_s.qps';'cvxqp3_l.qps';'cvxqp3_m.qps';'cvxqp3_s.qps';...
  'dtoc3.qps'; 'dual1.qps'; 'dual2.qps'; ...
  'dual3.qps'; 'dual4.qps'; 'dualc1.qps'; 'dualc2.qps'; 'dualc5.qps'; 'dualc8.qps'; 'genhs28.qps'; ...
  'gouldqp2.qps'; 'gouldqp3.qps'; 'hs21.qps'; 'hs35.qps'; 'hs35mod.qps'; 'hs51.qps'; ...
  'hs52.qps'; 'hs53.qps'; 'hs76.qps'; 'hs118.qps'; 'hs268.qps'; 'hue s- mod.qps'; 'huestis.qps'; 'ksip.qps'; ...
  'liswet1.qps'; 'liswet2.qps'; 'liswet3.qps'; 'liswet4.qps'; 'liswet5.qps'; 'liswet6.qps'; ...
  'liswet7.qps'; 'liswet8.qps'; 'liswet9.qps'; 'liswet10.qps'; 'liswet11.qps'; 'liswet12.qps'; ...
  'lotschd.qps'; 'mosarqp1.qps'; 'mosarqp2.qps'; 'powell20.qps'; 'primal1.qps'; 'primal2.qps'; ...
  'primal3.qps'; 'primal4.qps'; 'primalc1.qps'; 'primalc2.qps'; 'primalc5.qps'; 'primalc8.qps'; ...
  'qpcblend.qps'; 'qpcboei1.qps'; 'qpcboei2.qps'; 'qpcstair.qps'; 's268.qps'; 'stcqp1.qps'; ...
  'stcqp2.qps'; 'tame.qps'; 'ubh1.qps'; 'yao.qps'; 'zecevic2.qps'};

problem_qp_misc = {'boyd1.qps'; 'boyd2.qps'; 'con t- 050.qps'; 'con t- 100.qps'; 'con t- 101.qps'; 'con t- 200.qps'; 'con t- 201.qps'; 'con t- 300.qps'; ...
      'dpklo1.qps'; 'exdata.qps'; 'laser.qps'; 'qptest.qps'; 'selfqmin.qps'; 'stadat1.qps'; 'stadat2.qps'; ...
      'stadat3.qps'; 'values.qps'};

problem_qps_cute = {'aug2d.qps';'aug2dc.qps';'aug2dcqp.qps';'aug2dqp.qps';...
  'aug3d.qps';'aug3dc.qps';'aug3dcqp.qps';'aug3dqp.qps';...
  'dtoc3.qps';'hs21.qps';'hs118.qps'; 'hue s- mod.qps'; 'huestis.qps'; 'ksip.qps'; ...
  'liswet1.qps'; 'liswet2.qps'; 'liswet3.qps'; 'liswet4.qps'; 'liswet5.qps'; 'liswet6.qps'; ...
  'liswet7.qps'; 'liswet8.qps'; 'liswet9.qps'; 'liswet10.qps'; 'liswet11.qps'; 'liswet12.qps'; ...
  'lotschd.qps'; 'powell20.qps'; 'primal1.qps'; 'primal2.qps'; ...
  'primal3.qps'; 'primal4.qps'; 'primalc1.qps'; 'primalc2.qps'; 'primalc5.qps'; 'primalc8.qps'; ...
  'qpcblend.qps'; 'qpcboei1.qps'; 'qpcboei2.qps'; 'qpcstair.qps';'ubh1.qps'; 'yao.qps'; 'zecevic2.qps'};

problem_qps_misc = {'boyd1.qps'; 'boyd2.qps'; 'con t- 050.qps'; 'con t- 100.qps'; 'con t- 101.qps'; 'con t- 200.qps'; 'con t- 201.qps'; 'con t- 300.qps'; ...
      'dpklo1.qps'; 'selfqmin.qps'; 'stadat1.qps'; 'stadat2.qps'; ...
      'stadat3.qps'};
