function newclass = format_template(formulation, solver)

  template = ['classdef pdco_%s_%s < pdcoO & %s & %s\n'     ...
              '  properties\n'                              ...
              '  end\n\n'                                   ...
              '  methods\n'                                 ...
              '  function o = pdco_%s_%s(slack, options_pdco, options_form, options_solv)\n' ...
              '    o = o@pdcoO(slack, options_pdco);\n'     ...
              '    o = o@%s(options_form);\n'        ...
              '    o = o@%s(options_solv);\n'        ...
              '  end\n'                                     ...
              '  end\n'                                     ...
              'end\n'];

  newclass = sprintf(template,            ...
                     formulation, solver, ...
                     formulation, solver, ...
                     formulation, solver, ...
                     formulation, solver);

end
