function newclass = format_template(formulation, solver)

  template = ['classdef pdco_%s_%s < %s & %s\n'             ...
              '  properties\n'                              ...
              '  end\n\n'                                   ...
              '  methods\n'                                 ...
              '  function o = pdco_%s_%s(slack, options)\n' ...
              '    o = o@%s(slack, options);\n'             ...
              '    o = o@%s(slack, options);\n'             ...
              '  end\n'                                     ...
              '  end\n'                                     ...
              'end\n'];

  newclass = sprintf(template,            ...
                     formulation, solver, ...
                     formulation, solver, ...
                     formulation, solver, ...
                     formulation, solver);

end
